//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class AdminDashboard
{
    protected global::System.Web.UI.WebControls.Literal litTotalEmployers;
    protected global::System.Web.UI.WebControls.Literal litTotalSeekers;
    protected global::System.Web.UI.WebControls.Literal litTotalJobs;
    protected global::System.Web.UI.WebControls.Literal litTotalApplications;
    protected global::System.Web.UI.WebControls.Panel pnlData;
    protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    protected global::System.Web.UI.WebControls.Repeater rptJobs;
    protected global::System.Web.UI.WebControls.Repeater rptUsers;
    protected global::System.Web.UI.WebControls.DropDownList ddlJobStatusFilter;
}
