//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class HeaderControl
{
    protected global::System.Web.UI.WebControls.PlaceHolder phLoggedOutDesktop;
    protected global::System.Web.UI.WebControls.PlaceHolder phLoggedOutMobile;
    protected global::System.Web.UI.WebControls.PlaceHolder phJobSeekerDesktop;
    protected global::System.Web.UI.WebControls.PlaceHolder phJobSeekerMobile;
    protected global::System.Web.UI.WebControls.PlaceHolder phEmployerDesktop;
    protected global::System.Web.UI.WebControls.PlaceHolder phEmployerMobile;
    protected global::System.Web.UI.WebControls.PlaceHolder phEmployerLinksDesktop;
    protected global::System.Web.UI.WebControls.PlaceHolder phEmployerLinksMobile;
    protected global::System.Web.UI.WebControls.PlaceHolder phAdminDesktop;
    protected global::System.Web.UI.WebControls.PlaceHolder phAdminMobile;
    protected global::System.Web.UI.WebControls.PlaceHolder phAdminLinksDesktop;
    protected global::System.Web.UI.WebControls.PlaceHolder phAdminLinksMobile;
    protected global::System.Web.UI.WebControls.PlaceHolder phDefaultLinksDesktop;
    protected global::System.Web.UI.WebControls.PlaceHolder phDefaultLinksMobile;
    protected global::System.Web.UI.WebControls.Button btnLogout;
}
