//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class JobDetails
{
    protected global::System.Web.UI.WebControls.Literal litTitle;
    protected global::System.Web.UI.WebControls.Literal litJobTitle;
    protected global::System.Web.UI.WebControls.Literal litCompany;
    protected global::System.Web.UI.WebControls.Literal litLocation;
    protected global::System.Web.UI.WebControls.Literal litJobType;
    protected global::System.Web.UI.WebControls.Literal litSalary;
    protected global::System.Web.UI.WebControls.Literal litPostedDate;
    protected global::System.Web.UI.WebControls.Literal litDescription;
    protected global::System.Web.UI.WebControls.Literal litRequirements;
    protected global::System.Web.UI.WebControls.Literal litApplyMessage;
    protected global::System.Web.UI.WebControls.Button btnApply;
}
