//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class JobSeekerDashboard
{
    protected global::System.Web.UI.WebControls.Label lblUserName;
    protected global::System.Web.UI.WebControls.Label lblFullName;
    protected global::System.Web.UI.WebControls.Label lblQualification;
    protected global::System.Web.UI.WebControls.Image imgProfile;
    protected global::System.Web.UI.WebControls.Repeater rptSkills;
    protected global::System.Web.UI.WebControls.Repeater rptRecommendedJobs;
    protected global::System.Web.UI.WebControls.Repeater rptRecentApplications;


}
