//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Login
{
    protected global::System.Web.UI.WebControls.TextBox UsernameTextBox;
    protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;
    protected global::System.Web.UI.WebControls.CheckBox RememberMeCheckBox;
    protected global::System.Web.UI.WebControls.Button LoginButton;
    protected global::System.Web.UI.WebControls.Label LoginMessageLabel;
}
