//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class MyApplications
{
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
    protected global::System.Web.UI.WebControls.Button btnBrowseJobs;
    protected global::System.Web.UI.WebControls.Panel pnlApplications;
    protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    protected global::System.Web.UI.WebControls.Repeater rptApplications;
}
