//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class PostJob
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.Panel pnlSuccess;
    protected global::System.Web.UI.WebControls.Panel pnlForm;

    // Basic Job Details
    protected global::System.Web.UI.WebControls.TextBox txtJobTitle;
    protected global::System.Web.UI.WebControls.TextBox txtJobDescription;
    protected global::System.Web.UI.WebControls.DropDownList ddlJobCategory;
    protected global::System.Web.UI.WebControls.DropDownList ddlJobType;
    protected global::System.Web.UI.WebControls.TextBox txtDeadline;

    // Requirements
    protected global::System.Web.UI.WebControls.DropDownList ddlQualification;
    protected global::System.Web.UI.WebControls.DropDownList ddlExperience;
    protected global::System.Web.UI.WebControls.CheckBoxList cblSkills;

    // Location & Salary
    protected global::System.Web.UI.WebControls.TextBox txtLocation;
    protected global::System.Web.UI.WebControls.TextBox txtSalary;

    // Preview Literals
    protected global::System.Web.UI.WebControls.Literal litPreviewTitle;
    protected global::System.Web.UI.WebControls.Literal litPreviewCompany;
    protected global::System.Web.UI.WebControls.Literal litPreviewLocation;
    protected global::System.Web.UI.WebControls.Literal litPreviewJobType;
    protected global::System.Web.UI.WebControls.Literal litPreviewCategory;
    protected global::System.Web.UI.WebControls.Literal litPreviewSalary;
    protected global::System.Web.UI.WebControls.Literal litPreviewSkills;
    protected global::System.Web.UI.WebControls.Literal litPreviewQualification;
    protected global::System.Web.UI.WebControls.Literal litPreviewExperience;
    protected global::System.Web.UI.WebControls.Literal litPreviewDescription;
    protected global::System.Web.UI.WebControls.Literal litPreviewPostedDate;
    protected global::System.Web.UI.WebControls.Literal litPreviewDeadline;

    // Action Buttons
    protected global::System.Web.UI.WebControls.Button btnPreview;
    protected global::System.Web.UI.WebControls.Button btnSaveDraft;
    protected global::System.Web.UI.WebControls.Button btnPublish;
}
