//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Registration
{
    protected global::System.Web.UI.WebControls.TextBox NameTextBox;
    protected global::System.Web.UI.WebControls.TextBox UsernameTextBox;
    protected global::System.Web.UI.WebControls.TextBox EmailTextBox;
    protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;
    protected global::System.Web.UI.WebControls.TextBox ConfirmPasswordTextBox;
    protected global::System.Web.UI.WebControls.RadioButton JobSeekerRadioButton;
    protected global::System.Web.UI.WebControls.RadioButton CompanyRadioButton;
    protected global::System.Web.UI.WebControls.CheckBox RememberMeCheckBox;
    protected global::System.Web.UI.WebControls.Button RegisterButton;
    protected global::System.Web.UI.WebControls.Label RegisterMessageLabel;
}
