//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Reports
{
    protected global::System.Web.UI.WebControls.Literal litTotalSeekers;
    protected global::System.Web.UI.WebControls.Literal litTotalEmployers;
    protected global::System.Web.UI.WebControls.Literal litTotalJobs;
    protected global::System.Web.UI.WebControls.Literal litTotalApplications;

    protected global::System.Web.UI.WebControls.Repeater rptJobDistribution;
    protected global::System.Web.UI.WebControls.Repeater rptEmployerActivity;
    protected global::System.Web.UI.WebControls.Repeater rptApplicationReport;
}
